from typing import Protocol, AsyncGenerator, Any
import numpy as np

class AudioSource(Protocol):
    """Provides a stream of audio chunks."""
    async def get_audio_stream(self) -> AsyncGenerator[np.ndarray, None]: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...

class WakeWordDetector(Protocol):
    """Detects a wake word in an audio stream."""
    def detect(self, audio_chunk: np.ndarray) -> bool: ...

class VoiceActivityDetector(Protocol):
    """Detects voice activity in an audio chunk."""
    def is_speech(self, audio_chunk: np.ndarray) -> bool: ...

class SpeechRecognizer(Protocol):
    """Converts audio to text."""
    async def transcribe(self, audio_data: np.ndarray) -> str: ...

class TextToSpeech(Protocol):
    """Converts text to audio."""
    async def synthesize(self, text: str) -> np.ndarray: ...
    async def synthesize_stream(self, text: str) -> AsyncGenerator[np.ndarray, None]: ...
