from typing import Protocol, List, Optional, Dict
from .models import Point, ScreenFrame, ComputerState

class ApplicationController(Protocol):
    async def list_applications(self) -> List[str]: ...
    async def open_application(self, name: str) -> None: ...
    async def close_application(self, name: str) -> None: ...
    async def is_application_running(self, name: str) -> bool: ...
    async def get_application_info(self, name: str) -> Dict: ...
    async def get_active_application(self) -> Optional[str]: ...

class WindowController(Protocol):
    async def list_windows(self) -> List[Dict]: ...
    async def get_active_window(self) -> Optional[Dict]: ...
    async def focus_window(self, window_id: str) -> None: ...
    async def minimize_window(self, window_id: str) -> None: ...
    async def maximize_window(self, window_id: str) -> None: ...
    async def restore_window(self, window_id: str) -> None: ...
    async def move_window(self, window_id: str, x: int, y: int) -> None: ...
    async def resize_window(self, window_id: str, width: int, height: int) -> None: ...

class MouseController(Protocol):
    async def move(self, point: Point) -> None: ...
    async def click(self, button: str = "left") -> None: ...
    async def double_click(self, button: str = "left") -> None: ...
    async def right_click(self) -> None: ...
    async def scroll(self, clicks: int) -> None: ...
    async def drag(self, start: Point, end: Point) -> None: ...
    async def get_position(self) -> Point: ...

class KeyboardController(Protocol):
    async def type_text(self, text: str) -> None: ...
    async def press_key(self, key: str) -> None: ...
    async def key_down(self, key: str) -> None: ...
    async def key_up(self, key: str) -> None: ...
    async def hotkey(self, keys: List[str]) -> None: ...

class ClipboardController(Protocol):
    async def read_clipboard(self) -> str: ...
    async def write_clipboard(self, text: str) -> None: ...
    async def clear_clipboard(self) -> None: ...

class ScreenCaptureService(Protocol):
    async def capture_primary_screen(self) -> ScreenFrame: ...
    async def capture_all_screens(self) -> List[ScreenFrame]: ...
    async def capture_region(self, x: int, y: int, width: int, height: int) -> ScreenFrame: ...
    async def get_screen_dimensions(self) -> Dict[str, int]: ...
    async def list_displays(self) -> List[str]: ...

class BrowserController(Protocol):
    async def open_url(self, url: str) -> None: ...
    async def get_current_url(self) -> str: ...
    async def get_page_title(self) -> str: ...
    async def navigate(self, url: str) -> None: ...
    async def go_back(self) -> None: ...
    async def go_forward(self) -> None: ...
    async def refresh(self) -> None: ...
    async def click(self, selector: str) -> None: ...
    async def type(self, selector: str, text: str) -> None: ...
    async def scroll(self, amount: int) -> None: ...

class ComputerObserver(Protocol):
    async def get_state(self) -> ComputerState: ...

class ComputerController(Protocol):
    """The central root for all computer intelligence capabilities."""
    @property
    def application(self) -> ApplicationController: ...
    
    @property
    def window(self) -> WindowController: ...
    
    @property
    def mouse(self) -> MouseController: ...
    
    @property
    def keyboard(self) -> KeyboardController: ...
    
    @property
    def clipboard(self) -> ClipboardController: ...
    
    @property
    def screen(self) -> ScreenCaptureService: ...
    
    @property
    def observer(self) -> ComputerObserver: ...
    
    @property
    def browser(self) -> BrowserController: ...
