from enum import Enum
from typing import Any
from pydantic import BaseModel, Field
from datetime import datetime, timezone

class EventType(str, Enum):
    # Agent Loop Events
    SESSION_STARTED = "SESSION_STARTED"
    USER_MESSAGE_RECEIVED = "USER_MESSAGE_RECEIVED"
    AI_REQUEST_STARTED = "AI_REQUEST_STARTED"
    AI_RESPONSE_RECEIVED = "AI_RESPONSE_RECEIVED"
    TOOL_CALL_STARTED = "TOOL_CALL_STARTED"
    TOOL_CALL_COMPLETED = "TOOL_CALL_COMPLETED"
    TOOL_CALL_FAILED = "TOOL_CALL_FAILED"
    
    # Phase 2: Computer Events
    COMPUTER_ACTION_STARTED = "COMPUTER_ACTION_STARTED"
    COMPUTER_ACTION_COMPLETED = "COMPUTER_ACTION_COMPLETED"
    COMPUTER_ACTION_FAILED = "COMPUTER_ACTION_FAILED"
    APPLICATION_OPENED = "APPLICATION_OPENED"
    APPLICATION_CLOSED = "APPLICATION_CLOSED"
    WINDOW_FOCUSED = "WINDOW_FOCUSED"
    MOUSE_ACTION = "MOUSE_ACTION"
    KEYBOARD_ACTION = "KEYBOARD_ACTION"
    SCREEN_CAPTURE_STARTED = "SCREEN_CAPTURE_STARTED"
    SCREEN_CAPTURE_COMPLETED = "SCREEN_CAPTURE_COMPLETED"
    BROWSER_ACTION_STARTED = "BROWSER_ACTION_STARTED"
    BROWSER_ACTION_COMPLETED = "BROWSER_ACTION_COMPLETED"
    TASK_VERIFICATION_STARTED = "TASK_VERIFICATION_STARTED"
    TASK_VERIFICATION_COMPLETED = "TASK_VERIFICATION_COMPLETED"
    TASK_RECOVERY_STARTED = "TASK_RECOVERY_STARTED"
    PERMISSION_REQUIRED = "PERMISSION_REQUIRED"
    AGENT_TASK_STARTED = "AGENT_TASK_STARTED"
    AGENT_TASK_COMPLETED = "AGENT_TASK_COMPLETED"
    AGENT_ERROR = "AGENT_ERROR"
    
    # Phase 3: Voice & UI Events
    AGENT_STATE_CHANGED = "AGENT_STATE_CHANGED"
    VOICE_STARTED = "VOICE_STARTED"
    VOICE_ACTIVITY = "VOICE_ACTIVITY"
    TRANSCRIPT_PARTIAL = "TRANSCRIPT_PARTIAL"
    TRANSCRIPT_FINAL = "TRANSCRIPT_FINAL"
    TTS_STARTED = "TTS_STARTED"
    TTS_AUDIO_LEVEL = "TTS_AUDIO_LEVEL"
    TTS_TEXT = "TTS_TEXT"
    TTS_ENDED = "TTS_ENDED"
    TASK_STARTED = "TASK_STARTED"
    TASK_PROGRESS = "TASK_PROGRESS"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_FAILED = "TASK_FAILED"

class BaseEvent(BaseModel):
    """Base model for all events in KAHNA."""
    event_type: EventType
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    session_id: str | None = None
    payload: dict[str, Any] = Field(default_factory=dict)
